######################################################################
# Automatically generated by qmake (2.01a) ?? 4? 23 21:46:39 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += datastore.h
SOURCES += datastore.cpp main.cpp
